### ISSUE TITLE
Improve how we show auth logs in admin with a MySQL view

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#249]
We need to improve how we show logs in admin, without loading all of them all the time.

An approach is with a mysql view and ajax on data table.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
@andreipetcu I see this error on live

<img width="1759" alt="Screen Shot 2021-04-05 at 3 19 15 PM" src="https://user-images.githubusercontent.com/147089/113573233-64417d00-9622-11eb-9192-b69f018357cf.png">

**Comment by andreipetcu** [comment]
Fixed on development branch

**Comment by mariusghitoiu** [comment]
@andreipetcu still happens when sorting Încercări autentificare eșuate: activate to sort column ascending

See details in sentry https://sentry.io/organizations/citizennext/issues/2358357233/?project=5563017&query=is%3Aunresolved

**Comment by mariusghitoiu** [comment]
Released.
